<a href="https://colab.research.google.com/github/farankhandev/flyrank-ml-internship/blob/main/work/notebooks/w07_action_playbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-10 — Content Action Playbook

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/farankhandev/flyrank-ml-internship/blob/main/work/notebooks/w07_action_playbook.ipynb)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Ranked actions + reason codes

The queue contains 200 content items ranked for potential refresh action. The recommendations are decision-support signals rather than automatic publishing decisions.

The largest action group is `refresh_and_review_ctr` with 130 items. These items are candidates for human review of click-through performance. A further 35 items are marked `refresh`, while 35 are marked `refresh_and_review_engagement`.

Confidence is high for 161 items and medium for 39 items. The trend signal is predominantly declining: 197 items are classified as `down`, 2 as `stable`, and 1 as `up`.

The most common reason codes are `model_decline_risk` and `visible_model_opportunity`, both appearing on all 200 items. `declining_with_demand` appears on 197 items. Low CTR is flagged for 130 items, while low engagement is flagged for 78 items. A smaller group of 21 items has `page_one_decay_risk`, and 1 item is marked as a stale visible page.

The ranking should be used to prioritize human review. The reason codes provide an interpretable explanation of the signals behind each recommended action.

In [ ]:
import pandas as pd

queue = pd.read_csv(
    "flyrank-ml-internship/outputs/refresh_queue_sample.csv"
)

print("Rows:", len(queue))
print("Columns:", list(queue.columns))

display(queue.head(10))

Rows: 200
Columns: ['final_rank', 'content_id', 'client_id', 'final_refresh_score', 'best_model_name', 'best_model_probability', 'baseline_refresh_score', 'confidence', 'suggested_action', 'final_reason_codes', 'is_declining_label', 'impressions_90d', 'clicks_90d', 'sessions_90d', 'avg_position', 'ctr', 'content_age_days', 'days_since_last_update', 'word_count', 'trend_direction', 'competition_level', 'content_type', 'main_intent', 'age_tier', 'freshness_tier', 'word_count_tier', 'impression_tier', 'position_tier']

,final_rank,content_id,client_id,final_refresh_score,best_model_name,best_model_probability,baseline_refresh_score,confidence,suggested_action,final_reason_codes,...,word_count,trend_direction,competition_level,content_type,main_intent,age_tier,freshness_tier,word_count_tier,impression_tier,position_tier
0,1,content_1f080331fa2b,client_3fdba35f04,81.636697,random_forest,0.782079,0.844481,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,...,1404.0,down,MEDIUM,keyword article,informational,91-180,91-180,1000-2000,good,page_1
1,2,content_6aa43079fb0c,client_3fdba35f04,81.447656,random_forest,0.788105,0.825477,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1457.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1
2,3,content_d6570c51c9bd,client_3fdba35f04,81.430346,random_forest,0.847372,0.695884,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1362.0,down,MEDIUM,keyword article,informational,91-180,91-180,1000-2000,moderate,striking
3,4,content_72e800a9c214,client_3fdba35f04,81.034960,random_forest,0.774371,0.842545,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1371.0,down,MEDIUM,keyword article,commercial,91-180,91-180,1000-2000,good,page_1
4,5,content_e04eb9549989,client_3fdba35f04,80.873188,random_forest,0.814805,0.749468,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1408.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1
5,6,content_b69288c5e701,client_3fdba35f04,80.754770,random_forest,0.795713,0.787358,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1370.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1
6,7,content_9b6df29f7889,client_3fdba35f04,80.632923,random_forest,0.846245,0.673530,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1415.0,down,MEDIUM,keyword article,commercial,91-180,91-180,1000-2000,moderate,page_1
7,8,content_bb6ebb5ec8c8,client_3fdba35f04,80.371236,random_forest,0.834638,0.690665,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1381.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,moderate,striking
8,9,content_4d76cdb3387b,client_3fdba35f04,80.362748,random_forest,0.843092,0.671993,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1554.0,down,HIGH,keyword article,commercial,91-180,91-180,1000-2000,moderate,top_3
9,10,content_b4f35d640b1c,client_3fdba35f04,80.321757,random_forest,0.843803,0.669168,medium,refresh,declining_with_demand|model_decline_risk|visib...,...,1389.0,down,HIGH,keyword article,commercial,91-180,91-180,1000-2000,good,page_3_5

In [ ]:


ranked_queue = (
    queue[
        [
            "final_rank",
            "content_id",
            "final_refresh_score",
            "confidence",
            "suggested_action",
            "final_reason_codes",
            "trend_direction",
        ]
    ]
    .sort_values("final_rank")
)

display(ranked_queue.head(20))

,final_rank,content_id,final_refresh_score,confidence,suggested_action,final_reason_codes,trend_direction
0,1,content_1f080331fa2b,81.636697,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,down
1,2,content_6aa43079fb0c,81.447656,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
2,3,content_d6570c51c9bd,81.430346,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
3,4,content_72e800a9c214,81.034960,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
4,5,content_e04eb9549989,80.873188,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
5,6,content_b69288c5e701,80.754770,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
6,7,content_9b6df29f7889,80.632923,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
7,8,content_bb6ebb5ec8c8,80.371236,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
8,9,content_4d76cdb3387b,80.362748,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
9,10,content_b4f35d640b1c,80.321757,medium,refresh,declining_with_demand|model_decline_risk|visib...,down
10,11,content_ba6f9dfcbca1,80.282275,medium,refresh,declining_with_demand|model_decline_risk|visib...,down
11,12,content_1b51115391a3,80.134145,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
12,13,content_e76ac7fed711,80.062755,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
13,14,content_b1d593faf9c6,79.957743,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,down
14,15,content_20ddbdfbbd90,79.878200,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,down
15,16,content_73b70737ee63,79.875242,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
16,17,content_81e59177b59a,79.601277,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
17,18,content_91fefd1726b3,79.562384,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down
18,19,content_aa76dcfed6e7,79.557090,high,refresh_and_review_engagement,declining_with_demand|low_engagement_visible_p...,down
19,20,content_03475a5923fe,79.539037,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down

In [ ]:


action_summary = (
    queue["suggested_action"]
    .value_counts()
    .rename_axis("suggested_action")
    .reset_index(name="count")
)

confidence_summary = (
    queue["confidence"]
    .value_counts()
    .rename_axis("confidence")
    .reset_index(name="count")
)

trend_summary = (
    queue["trend_direction"]
    .value_counts()
    .rename_axis("trend_direction")
    .reset_index(name="count")
)

reason_summary = (
    queue["final_reason_codes"]
    .str.split("|")
    .explode()
    .value_counts()
    .rename_axis("reason_code")
    .reset_index(name="count")
)

print("Suggested actions")
display(action_summary)

print("Confidence")
display(confidence_summary)

print("Trend direction")
display(trend_summary)

print("Reason codes")
display(reason_summary)

Suggested actions

                suggested_action  count
0         refresh_and_review_ctr    130
1                        refresh     35
2  refresh_and_review_engagement     35

Confidence

  confidence  count
0       high    161
1     medium     39

Trend direction

  trend_direction  count
0            down    197
1          stable      2
2              up      1

Reason codes

                   reason_code  count
0    visible_model_opportunity    200
1           model_decline_risk    200
2        declining_with_demand    197
3         low_ctr_visible_page    130
4         ctr_review_candidate    130
5  low_engagement_visible_page     78
6  engagement_review_candidate     78
7          page_one_decay_risk     21
8           stale_visible_page      1

## 2. Intended use and limits

This playbook is intended to help a content or SEO reviewer prioritize pages for possible refresh. It combines the ranked refresh score, model risk signals, trend direction, confidence, and reason codes to support review decisions.

The queue is a prioritization tool, not an automatic publishing system. A high-ranked item means it should be reviewed earlier; it does not guarantee that a content change will improve performance.

The recommendations are based on the available dataset and observed signals. They should not be treated as causal conclusions or guaranteed future outcomes.

The playbook should not be used to automatically rewrite, publish, remove, or materially change content without human review. Business context, search intent, content quality, current information, and other factors should be checked before action.

In [ ]:


print("Intended use:")
print("- Prioritize content for human review.")
print("- Use model and observed signals to support refresh decisions.")
print("- Treat recommendations as directional decision support.")

print("\nLimits:")
print("- A high score does not guarantee improvement.")
print("- Model predictions are not causal evidence.")
print("- Recommendations should not trigger automatic publishing.")
print("- Human review is required before making content changes.")

Intended use:
- Prioritize content for human review.
- Use model and observed signals to support refresh decisions.
- Treat recommendations as directional decision support.

Limits:
- A high score does not guarantee improvement.
- Model predictions are not causal evidence.
- Recommendations should not trigger automatic publishing.
- Human review is required before making content changes.

## 3. Human review + the no-go list

Every recommended action should be reviewed by a person before implementation. The reviewer should check the content context, search intent, current information, page quality, and whether the reason codes match what is actually visible on the page.

### Human review rules

* Review high-ranked items first.
* Confirm the reason codes before taking action.
* Check whether the page still matches the intended search intent.
* Review CTR or engagement signals before changing the content.
* Check for outdated or inaccurate information.
* Record the decision and the action taken.
* Treat medium-confidence recommendations as requiring additional scrutiny.

### No-go list

The system should **not** automatically:

* Publish or replace content.
* Delete pages.
* Change important business claims.
* Make decisions about sensitive or high-impact topics.
* Override human editorial judgment.
* Treat model predictions as guaranteed outcomes.
* Make large-scale content changes without human review.

The playbook is designed to support human decisions, not replace them.

In [ ]:
review_rules = [
    "Review high-ranked items first.",
    "Confirm reason codes before taking action.",
    "Check search intent and page quality.",
    "Review CTR or engagement signals.",
    "Check for outdated or inaccurate information.",
    "Give additional scrutiny to medium-confidence items.",
]

no_go = [
    "Automatic publishing or replacement",
    "Automatic page deletion",
    "Changing important business claims without review",
    "Large-scale content changes without human review",
    "Overriding editorial judgment",
    "Treating model predictions as guaranteed outcomes",
]

print("Human review rules:")
for rule in review_rules:
    print(f"- {rule}")

print("\nNo-go list:")
for item in no_go:
    print(f"- {item}")

Human review rules:
- Review high-ranked items first.
- Confirm reason codes before taking action.
- Check search intent and page quality.
- Review CTR or engagement signals.
- Check for outdated or inaccurate information.
- Give additional scrutiny to medium-confidence items.

No-go list:
- Automatic publishing or replacement
- Automatic page deletion
- Changing important business claims without review
- Large-scale content changes without human review
- Overriding editorial judgment
- Treating model predictions as guaranteed outcomes

## 4. Monitoring / retrain triggers

The recommendations should be monitored over time because content performance and search conditions can change.

The playbook should be reviewed when:

* The distribution of content trends changes substantially.
* CTR or engagement patterns change from the patterns used to create the recommendations.
* A large number of recommendations no longer match human reviewer judgment.
* Model confidence becomes consistently lower.
* New content types or substantially different content characteristics appear.
* Model performance on newly available validation data declines.

A retraining review should be considered when these signals indicate that the existing model or recommendation rules may no longer represent current content behavior.

These triggers are monitoring guidelines, not automatic retraining commands. A human should review the evidence before deciding whether retraining is necessary.

In [ ]:


monitoring_triggers = [
    "Content trend distribution changes substantially.",
    "CTR or engagement patterns change.",
    "Recommendations frequently disagree with human review.",
    "Model confidence becomes consistently lower.",
    "New content types or substantially different content appear.",
    "Model performance declines on new validation data.",
]

retrain_triggers = [
    "Evidence suggests the current model no longer represents current content behavior.",
    "New validation results show meaningful performance deterioration.",
]

print("Monitoring triggers:")
for trigger in monitoring_triggers:
    print(f"- {trigger}")

print("\nRetrain review triggers:")
for trigger in retrain_triggers:
    print(f"- {trigger}")

Monitoring triggers:
- Content trend distribution changes substantially.
- CTR or engagement patterns change.
- Recommendations frequently disagree with human review.
- Model confidence becomes consistently lower.
- New content types or substantially different content appear.
- Model performance declines on new validation data.

Retrain review triggers:
- Evidence suggests the current model no longer represents current content behavior.
- New validation results show meaningful performance deterioration.

## 5. Exports for the paper

The ranked action queue is exported for reuse in the research paper. The export preserves the ranking, recommended action, confidence, reason codes, and supporting signals used for prioritization.

The queue is regenerated by the notebook rather than manually maintained. Reusable figures can also be saved under `work/figures/`.

The exported files are intended as research-paper inputs and are not production deployment artifacts.

In [ ]:
import os

output_dir = "flyrank-ml-internship/work/outputs"
os.makedirs(output_dir, exist_ok=True)

export_columns = [
    "final_rank",
    "content_id",
    "final_refresh_score",
    "confidence",
    "suggested_action",
    "final_reason_codes",
    "trend_direction",
    "impressions_90d",
    "clicks_90d",
    "sessions_90d",
    "avg_position",
    "ctr",
]

paper_queue = queue[export_columns].sort_values("final_rank")

output_path = os.path.join(output_dir, "action_playbook_queue.csv")

paper_queue.to_csv(output_path, index=False)

print(f"Exported {len(paper_queue)} rows to:")
print(output_path)

display(paper_queue.head(10))

Exported 200 rows to:
flyrank-ml-internship/work/outputs/action_playbook_queue.csv

,final_rank,content_id,final_refresh_score,confidence,suggested_action,final_reason_codes,trend_direction,impressions_90d,clicks_90d,sessions_90d,avg_position,ctr
0,1,content_1f080331fa2b,81.636697,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,down,12834,6,66,6.8,0.05
1,2,content_6aa43079fb0c,81.447656,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down,8064,6,23,3.8,0.07
2,3,content_d6570c51c9bd,81.430346,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down,2498,0,9,10.1,0.00
3,4,content_72e800a9c214,81.034960,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down,13790,16,27,8.2,0.12
4,5,content_e04eb9549989,80.873188,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down,3393,3,5,3.6,0.09
5,6,content_b69288c5e701,80.754770,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down,5811,4,14,6.4,0.07
6,7,content_9b6df29f7889,80.632923,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down,1622,2,20,3.1,0.12
7,8,content_bb6ebb5ec8c8,80.371236,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down,2621,0,10,12.8,0.00
8,9,content_4d76cdb3387b,80.362748,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,down,1597,2,5,2.7,0.13
9,10,content_b4f35d640b1c,80.321757,medium,refresh,declining_with_demand|model_decline_risk|visib...,down,3867,2,5,27.5,0.05

## Self-check

* All required sections are filled with markdown explanations and supporting code.
* The ranked action queue contains 200 items.
* Intended use, limitations, human review rules, no-go cases, and monitoring/retrain triggers are documented.
* The ranked queue is exported for reuse in the research paper.
* The recommendations are presented as decision-support signals rather than guaranteed outcomes.
* The notebook is intended for research and planning, not production automation.